name: countdown_app
description: A Flutter countdown app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.0
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  permission_handler: ^11.0.0
  elegant_notification: ^1.11.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
